#!/bin/sh

set -e

# Dependencies
apk add --no-cache bash openjdk8-jre-base supervisor

# Download & Extract
kafka_url="https://archive.apache.org/dist/kafka/1.0.0/kafka_2.11-1.0.0.tgz"
zookeeper_url="https://archive.apache.org/dist/zookeeper/zookeeper-3.4.11/zookeeper-3.4.11.tar.gz"

mkdir -p /root/build
cd /root/build

wget -q "$kafka_url" -O kafka.tar.gz
wget -q "$zookeeper_url" -O zookeeper.tar.gz

mkdir -p /opt/kafka
tar --strip-components 1 -x -C /opt/kafka -f kafka.tar.gz

mkdir -p /opt/zookeeper
tar --strip-components 1 -x -C /opt/zookeeper -f zookeeper.tar.gz

# Directories & Permissions
chmod -R a+rw /opt

# Clean up
cd /
rm -rf /root/build

